Resources:
  MyECRRepositoryTemplate:
    Type: AWS::ECR::RepositoryCreationTemplate
    Properties:
      AppliedFor:
        - "production"
        - "staging"
      CustomRoleArn: "arn:aws:iam::123456789012:role/ECRRepositoryRole"
      Description: "Repository template for ERC"
      EncryptionConfiguration:
        EncryptionType: "AES256"
      ImageTagMutability: "IMMUTABLE"
      LifecyclePolicy: |
        {
          "rules": [
            {
              "rulePriority": 1,
              "description": "Expire untagged images older than 30 days",
              "selection": {
                "tagStatus": "untagged",
                "countType": "sinceImagePushed",
                "countUnit": "days",
                "countNumber": 30
              },
              "action": {
                "type": "expire"
              }
            }
          ]
        }
      Prefix: "my-erc-"
      RepositoryPolicy: |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "AllowPull",
              "Effect": "Allow",
              "Principal": "*",
              "Action": [
                "ecr:BatchCheckLayerAvailability",
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage"
              ]
            }
          ]
        }
      ResourceTags:
        - Key: "Environment"
          Value: "Production"
