# ECR Repository for Docker images
template-file-path: ./main-stack-inline.yaml
stack-name: ct-inline-stack
tags:
    Name: "ct-development-inline-automated"
    Project: "ct-aws-cfn-sync"
parameters:
    ECRRepositoryName: "ct-nginx-app"
    ECSClusterName: "ct-ecs-cluster"
    VpcId: "vpc-0024a1a5be8a956f4"
    Subnet1: "subnet-000c94e10132347e1"
    Subnet2: "subnet-004f125288c161a98"
# # ECS Cluster for container deployment
# ecs-cluster:
#   template-file-path: ./ecs-cluster.yaml
#   stack-name: ct-ecs-stack
#   tags:
#     Name: 'ct-development-ecs-automated'
#     Project: 'ct-aws-cfn-sync'
#   parameters:
#     ClusterName: 'ct-ecs-cluster'
#     ContainerImage: '${ECR_REPOSITORY_URI}:latest'
# These will be populated dynamically during deployment
# VpcId: ${VPC_ID}
# PublicSubnet1Id: ${PUBLIC_SUBNET_1}
# PublicSubnet2Id: ${PUBLIC_SUBNET_2}
