# ECR Repository for Docker images
template-file-path: ./main-stack.yaml
stack-name: ct-main-stack
tags:
    Name: "ct-development-main-automated"
    Project: "ct-aws-cfn-sync"
parameters:
    ECRRepositoryName: "ct-nginx-app"
    ECSClusterName: "ct-ecs-cluster"
    TemplateBucket: "ct-cfn-templates-bucket"
# # ECS Cluster for container deployment
# ecs-cluster:
#   template-file-path: ./ecs-cluster.yaml
#   stack-name: ct-ecs-stack
#   tags:
#     Name: 'ct-development-ecs-automated'
#     Project: 'ct-aws-cfn-sync'
#   parameters:
#     ClusterName: 'ct-ecs-cluster'
#     ContainerImage: '${ECR_REPOSITORY_URI}:latest'
# These will be populated dynamically during deployment
# VpcId: ${VPC_ID}
# PublicSubnet1Id: ${PUBLIC_SUBNET_1}
# PublicSubnet2Id: ${PUBLIC_SUBNET_2}
