# ECR Repository for Docker images
template-file-path: ./main-stack.yaml
stack-name: ct-nested-stack
tags:
    Name: "ct-development-nested-automated"
    Project: "ct-aws-cfn-sync"
parameters:
    ECRRepositoryName: "ct-nginx-app"
    ECSClusterName: "ct-ecs-cluster"
    VpcId: "vpc-0df0f7a9a3a9d39ad"
    Subnet1: "subnet-07b8d4de7cbfd9d80"
    Subnet2: "subnet-0aa4e302da3a8b2e3"
# # ECS Cluster for container deployment
# ecs-cluster:
#   template-file-path: ./ecs-cluster.yaml
#   stack-name: ct-ecs-stack
#   tags:
#     Name: 'ct-development-ecs-automated'
#     Project: 'ct-aws-cfn-sync'
#   parameters:
#     ClusterName: 'ct-ecs-cluster'
#     ContainerImage: '${ECR_REPOSITORY_URI}:latest'
# These will be populated dynamically during deployment
# VpcId: ${VPC_ID}
# PublicSubnet1Id: ${PUBLIC_SUBNET_1}
# PublicSubnet2Id: ${PUBLIC_SUBNET_2}
