AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for Amazon ECR repository'

Parameters:
  RepositoryName:
    Type: String
    Default: 'nginx-app'
    Description: 'Name of the ECR repository'

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      ImageScanningConfiguration:
        ScanOnPush: true
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Keep only the last 5 images",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 5
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  RepositoryName:
    Description: 'Name of the ECR repository'
    Value: !Ref ECRRepository
  
  RepositoryURI:
    Description: 'URI of the ECR repository'
    Value: !GetAtt ECRRepository.RepositoryUri 