AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main CloudFormation template with nested stacks for VPC, ECR, and ECS'

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair for SSH access
  
  ECRRepositoryName:
    Type: String
    Default: 'ct-nginx-app'
    Description: Name of the ECR repository
  
  ECSClusterName:
    Type: String
    Default: 'ct-ecs-cluster'
    Description: Name of the ECS cluster

Resources:
  # First deploy the IAM permissions needed for ECR
  IAMPermissionsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ecr-iam-policy.yaml
      TimeoutInMinutes: 10
      Tags:
        - Key: Name
          Value: ct-iam-permissions-stack
        - Key: Project
          Value: ct-aws-cfn-sync

  # Then deploy the VPC infrastructure
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./cfn-template.yaml
      Parameters:
        KeyName: !Ref KeyName
      TimeoutInMinutes: 30
      Tags:
        - Key: Name
          Value: ct-development-vpc-automated
        - Key: Project
          Value: ct-aws-cfn-sync

  # Deploy the ECR repository
  ECRStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: 
      - IAMPermissionsStack
    Properties:
      TemplateURL: ./ecr-repository.yaml
      Parameters:
        RepositoryName: !Ref ECRRepositoryName
      TimeoutInMinutes: 10
      Tags:
        - Key: Name
          Value: ct-development-ecr-automated
        - Key: Project
          Value: ct-aws-cfn-sync

  # Finally deploy the ECS cluster
  ECSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VPCStack
      - ECRStack
    Properties:
      TemplateURL: ./ecs-cluster.yaml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnet1Id: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt VPCStack.Outputs.PublicSubnet2Id
        ClusterName: !Ref ECSClusterName
        ContainerImage: !Sub "${ECRStack.Outputs.RepositoryURI}:latest"
      TimeoutInMinutes: 30
      Tags:
        - Key: Name
          Value: ct-development-ecs-automated
        - Key: Project
          Value: ct-aws-cfn-sync

Outputs:
  VPCId:
    Description: 'VPC ID'
    Value: !GetAtt VPCStack.Outputs.VpcId
  
  ECRRepositoryURI:
    Description: 'URI of the ECR repository'
    Value: !GetAtt ECRStack.Outputs.RepositoryURI
  
  LoadBalancerDNS:
    Description: 'DNS name of the load balancer'
    Value: !GetAtt ECSStack.Outputs.LoadBalancerDNS 