AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main CloudFormation template with nested stacks for ECR and ECS'

Parameters:
  ECRRepositoryName:
    Type: String
    Default: 'ct-nginx-app'
    Description: 'Name of the ECR repository'
  
  ECSClusterName:
    Type: String
    Default: 'ct-ecs-cluster'
    Description: 'Name of the ECS cluster'
  
  VpcId:
    Type: String
    Description: 'VPC ID for the security group'
    Default: 'vpc-0df0f7a9a3a9d39ad'
  
  Subnet1:
    Type: String
    Description: 'First subnet ID for the ECS tasks'
    Default: 'subnet-07b8d4de7cbfd9d80'
  
  Subnet2:
    Type: String
    Description: 'Second subnet ID for the ECS tasks'
    Default: 'subnet-0aa4e302da3a8b2e3'
  
  S3BucketName:
    Type: String
    Description: 'S3 bucket containing nested stack templates'
    Default: 'ct-cfn-templates'
  
  S3KeyPrefix:
    Type: String
    Description: 'S3 key prefix for nested stack templates'
    Default: 'templates'

Resources:
  # ECR Repository Stack
  ECRStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${S3BucketName}.s3.amazonaws.com/${S3KeyPrefix}/ecr-repository.yaml'
      Parameters:
        RepositoryName: !Ref ECRRepositoryName
      TimeoutInMinutes: 10
      Tags:
        - Key: Name
          Value: ct-development-ecr-automated
        - Key: Project
          Value: ct-aws-cfn-sync

  # ECS Cluster Stack (depends on ECR Stack)
  ECSStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: ECRStack
    Properties:
      TemplateURL: !Sub 'https://${S3BucketName}.s3.amazonaws.com/${S3KeyPrefix}/ecs-cluster.yaml'
      Parameters:
        ClusterName: !Ref ECSClusterName
        ContainerImage: !Sub '${ECRStack.Outputs.RepositoryURI}:latest'
        VpcId: !Ref VpcId
        Subnet1: !Ref Subnet1
        Subnet2: !Ref Subnet2
      TimeoutInMinutes: 30
      Tags:
        - Key: Name
          Value: ct-development-ecs-automated
        - Key: Project
          Value: ct-aws-cfn-sync

Outputs:
  ECRRepositoryURI:
    Description: 'URI of the ECR repository'
    Value: !GetAtt ECRStack.Outputs.RepositoryURI
  
  ECSClusterName:
    Description: 'Name of the ECS cluster'
    Value: !GetAtt ECSStack.Outputs.ClusterName
  
  ECSServiceName:
    Description: 'Name of the ECS service'
    Value: !GetAtt ECSStack.Outputs.ServiceName 